logo: zhiwu5 # add logo name
title:zhiwu5！
description: > # this means to ignore newlines until "baseurl:"
  this is zhiwu5!
permalink: ':title/'
baseurl: "/zhiwu5/zhiwu5.github.io" # the subpath of your site, e.g. /blog
url: "https://zhiwu5.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: 平度一中2015级知务五班 # add banner title
banner-desc: we are family！ # add banner description

# Author settings
author-pic: face.jpg # your photo
author-name: # your name
about-author: # about author
email: your-email@domain.com # your email
phone: (496)-169-6557 # your pnone number
website: https://dwayne.example.com # you website

# Social link
google_url:    # add url link
twitter_url:   # add url link 
instagram_url: # add url link
pinterest_url: # add url link
dribbble_url:  # add url link
facebook_url:  # add url link

# Disqus
discus_identifier: mr-brown # add your discus identifier

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
